### ISSUE TITLE
issueデータ送信のワークフローファイルを作る

### ISSUE THREAD

**Issue by Saki-htr** [Saki-htr/fjord-choice#105]
### ゴール
- 補足したいすべてのイベントを入れたissueのワークフローファイルを作成する

**Comment by Saki-htr** [comment]
一旦完成したので、closeします。
```yaml
on:
  issues:
    types: [assigned, unassigned, labeled, unlabeled]

jobs:
  notify_line:
    runs-on: ubuntu-latest
    steps:
    - name: get assigned issue event
      env:
        ISSUE_ASSIGNEES: ${{ toJson(github.event.issue.assignees.*.id) }}
      run: |
        curl -X POST https://fjord-choice.herokuapp.com \
             -H 'Content-Type: application/json' \
             -d '{"number": ${{ github.event.issue.number }},
                  "labels": ${{ toJson(github.event.issue.labels.*.name) }},
                  "assignees": ${{ toJson(github.event.issue.assignees.*.id) }}
                  }'

```
